### Validate-OTP API Deployed

POST https://dikva7nni2.execute-api.us-east-2.amazonaws.com/api/v1/validateOtp HTTP/1.1
Content-Type: application/json

{
    "requestId": "123456543",
    "otpRequestId": "wertyuiyr23",
    "channelId": "LOGIN_MFA",
    "otp": "lsrjXOipsCRBeL8o5JZsLOG4OFcjqWprg4hYzdbKCh4="
}

### Validate-OTP API Local

POST http://localhost:3004/api/v1/validateOtp HTTP/1.1
Content-Type: application/json

{
    "requestId": "123456543",
    "otpRequestId": "wertyuiyr23",
    "channelId": "LOGIN_MFA",
    "otp": "lsrjXOipsCRBeL8o5JZsLOG4OFcjqWprg4hYzdbKCh4="
}